### ISSUE TITLE
适配新的beego，修复构建错误

### ISSUE THREAD

**Issue by zyfdegh** [lisijie/goblog#14]
我在用beego 1.7.2，执行构建时，会有一些地方不兼容了，需要改一下。

如
```sh
-       this.TplNames = this.moduleName + "/account/login.html"
+       this.TplName = this.moduleName + "/account/login.html"

// ...
-                       tagobj.Query().Filter("name__in", oldtags).Update(orm.Params{"count": orm.ColValue(orm.Col_Minus, 1)})
+                       tagobj.Query().Filter("name__in", oldtags).Update(orm.Params{"count": orm.ColValue(orm.ColMinus, 1)})

// ...
-       this.ServeJson()
+       this.ServeJSON()

// ...
-       if _, err := os.Stat(beego.ViewsPath + "/" + theme + "/layout.html"); err == nil {
+       if _, err := os.Stat(beego.BConfig.WebConfig.ViewsPath + "/" + theme + "/layout.html"); err == nil {

// ...
```

**Comment by xgfone** [comment]
**建议：** 使用 [`glide`](https://github.com/Masterminds/glide) 工具来管理一下所依赖库的版本，这样可避免由于依赖库中断 API 而导致的错误。

**Comment by xgfone** [comment]
参考我的一个项目配置：
```yaml
package: PACKAGE_NAME
owners:
  - name: xgfone
    email: xgfone@126.com
import:
  # The packages which have no dependence.
  - package: github.com/jessevdk/go-flags
    version: v1.1
  - package: github.com/xgfone/go-tools
    version: 0.26
  - package: github.com/fatih/structs
    version: dc3312cb1a4513a366c4c9e622ad55c32df12ed3
  - package: github.com/go-stack/stack
    version: v1.5.2

  # The packages which have dependency.
  # The depended packages precede the dependent packages.
  - package: github.com/mattn/go-isatty
    version: v0.0.1
  - package: github.com/mattn/go-colorable
    version: v0.0.6
  - package: github.com/inconshreveable/log15
    version: 46a701a619de90c65a78c04d1a58bf02585e9701
  - package: github.com/xgfone/go-utils
    version: 0.1

  # Others
  - package: golang.org/x/sys
    version: 478fcf54317e52ab69f40bb4c7a1520288d7f7ea
    repo: https://github.com/golang/sys
    vcs: git
```
注：我是先通过 `go list -json PACKAGE_NAME` 递归找出所有的依赖包，然后把它们都写在 `glide.yaml` 配置文件中。

获取依赖包：
```shell
$ cd /PATH/TO/PACKAGE_NAME
$ glide update
```

构建包：
```shell
$ go build PACKAGE_NAME
```
